[2021-10-26 04:34:48,163] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2021-10-25T00:00:00+00:00 [queued]>
[2021-10-26 04:34:48,179] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2021-10-25T00:00:00+00:00 [queued]>
[2021-10-26 04:34:48,180] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-26 04:34:48,180] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-26 04:34:48,181] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-26 04:34:48,190] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): accurate> on 2021-10-25 00:00:00+00:00
[2021-10-26 04:34:48,197] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2021-10-25T00:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp9_5p1mfa', '--error-file', '/tmp/tmply0c06km']
[2021-10-26 04:34:48,198] {standard_task_runner.py:77} INFO - Job 108: Subtask accurate
[2021-10-26 04:34:48,194] {standard_task_runner.py:52} INFO - Started process 9168 to run task
[2021-10-26 04:34:48,236] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate scheduled__2021-10-25T00:00:00+00:00 [running]> on host bd9f4a5cab42
[2021-10-26 04:34:48,273] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-25T00:00:00+00:00
[2021-10-26 04:34:48,275] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-26 04:34:48,276] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo accurate']
[2021-10-26 04:34:48,284] {subprocess.py:85} INFO - Output:
[2021-10-26 04:34:48,286] {subprocess.py:89} INFO - accurate
[2021-10-26 04:34:48,287] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-26 04:34:48,308] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20211025T000000, start_date=20211026T043448, end_date=20211026T043448
[2021-10-26 04:34:48,333] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-26 04:34:48,354] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
